"""Initial migration

Revision ID: b50cab70b91d
Revises: 
Create Date: 2026-04-26 16:08:00.343035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50cab70b91d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('violation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('violation_type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('fine_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qr_code_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violation_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_vehicle_number'), ['vehicle_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violation_vehicle_number'))
        batch_op.drop_index(batch_op.f('ix_violation_status'))
        batch_op.drop_index(batch_op.f('ix_violation_date'))

    op.drop_table('violation')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
